# Generated by Django 5.2.7 on 2025-10-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PYME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='PYME')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pymes_administradas', to=settings.AUTH_USER_MODEL)),
                ('empleados', models.ManyToManyField(blank=True, related_name='pymes_empleado', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pymes_propias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PyME',
                'verbose_name_plural': 'PyMEs',
            },
        ),
    ]
