# Generated by Django 5.2.7 on 2025-10-19 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancia_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salario_empleados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salario_admin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas_gastos', models.TextField(blank=True)),
                ('abierto_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_abiertos', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('empleados', models.ManyToManyField(related_name='turnos_asignados', to=settings.AUTH_USER_MODEL)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pyme')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=15)),
                ('codigo_transferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=17, null=True)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pyme')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.turno')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.venta')),
            ],
        ),
    ]
